version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always

  redis:
    image: redis:alpine
    command: redis-server --loglevel warning
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
